name: ci

on:
  workflow_dispatch:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        env:
          REPO_NAME: ${{ vars.REPO_NAME }}
          DOCKER_HUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        run: |
          - echo "Building and pushing docker image..."
          - REGISTRY_USER=$DOCKER_HUB_USERNAME REPO_NAME=$REPO_NAME docker buildx bake -f docker-bake.hcl --push